### ISSUE TITLE
Profiling fails is profile file does not exist

### ISSUE THREAD

**Issue by Valloric** [AtheMathmo/cpuprofiler#2]
``` rust
PROFILER.lock().unwrap().start("/tmp/prof.profile").unwrap();
[...code...]
PROFILER.lock().unwrap().stop().unwrap();
```

The above code fails with "No such file or directory" if the `/tmp/prof.profile` file does not already exists. This strikes me as poor usability; the file should be created if it doesn't exist and overwritten if it does.

**Comment by AtheMathmo** [comment]
I'll have to look into this - I'm fairly sure this should be covered by the [gperftools library](https://github.com/gperftools/gperftools). I'll try to reproduce on my end. If you're using '/tmp/prof.profile' it might be a permissions issue that isn't being reported correctly?

**Comment by Valloric** [comment]
I thought this might be the case, but other paths fail as well, including `./foo.profile` or anything else I try. I have to create the file with `touch` and only then will it work (and work great!; thanks for creating this).

**Comment by AtheMathmo** [comment]
I finally had some time to look into this. The issue is on the rust (my) side. I'm using the `fs::metadata` function to check that a file is valid before I pass the path over FFI.
