### ISSUE TITLE
Update version in README

### ISSUE THREAD

**Issue by fuine** [AtheMathmo/cpuprofiler#4]
Hi,
i took the version (`0.0.2`) from the `README.md`, after compiling and running my project i got an error regarding non-existing file, i searched through issues, i found the PR that fixed that, i then checked out the newest version on crates.io and finally installed `0.0.3` which works just fine.
I'd suggest bumping the version in the README file to avoid confusion for other people. Do you want to open a PR about that, or would you rather do that yourself?

Btw i find your crate immensely helpful in my current project :)

**Comment by AtheMathmo** [comment]
Ah, thanks for letting me know. I will just edit it in directly as it is such a minor change.

I'm glad this is helpful to you!

**Comment by fuine** [comment]
Great, thanks!
